### ISSUE TITLE
Adding / removing rows in a list 

### ISSUE THREAD

**Issue by gedw99** [shah-gaurav/flutter-data-binding#1]
Was playing around with lists / maps.
Say you have. List of customers.
The property changer does not work with lists ?

Could you let me know .
Maybe an example along with the counter ?

I like the .net inspired approach.
Will be interesting to bench it as I have also worked with ones that rely on an annotated data class to codegen the models with built in notification.

Ask me if curious

**Comment by shah-gaurav** [comment]
I apologize for the delay in response. Notifications were not turned on in GitHub so I didn't see your message earlier. 

Anyway, I have not found a way to auto generate events when the elements/contents of the list are updated. The function that is adding or removing the list item would have to emit the propertyChanged message to ensure that the Binding is notified and a rebuild occurs. I will try and add a simple example of this in the repo to demonstrate.

**Comment by gedw99** [comment]
this is great - thanks for the examples !!
